"""Seed example vendor applications for local demos."""

from decimal import Decimal

from django.core.management.base import BaseCommand

from apps.vendors.models.vendor import VendorApplication


class Command(BaseCommand):
    """Create a realistic set of vendor applications for demonstration."""

    help = "Seed vendor demo data (idempotent: avoids duplicates by tax ID)."

    def handle(self, *args, **options):
        demo_data = [
            (
                "Acme Supplies",
                "acme@example.com",
                "United States",
                "hardware",
                "US-ACME-001",
                Decimal("125000.00"),
                "medium",
                "submitted",
            ),
            (
                "Beta Consultancy",
                "beta@example.com",
                "United Kingdom",
                "consulting",
                "UK-BETA-002",
                Decimal("45000.00"),
                "low",
                "under_review",
            ),
            (
                "Gamma Software",
                "gamma@example.com",
                "Germany",
                "software",
                "DE-GAMMA-003",
                Decimal("200000.00"),
                "high",
                "changes_requested",
            ),
            (
                "Delta Facilities",
                "delta@example.com",
                "Canada",
                "facilities",
                "CA-DELTA-004",
                Decimal("78000.00"),
                "medium",
                "approved",
            ),
            (
                "Epsilon Services",
                "epsilon@example.com",
                "France",
                "services",
                "FR-EPSILON-005",
                Decimal("32000.00"),
                "low",
                "rejected",
            ),
            (
                "Zeta Hardware",
                "zeta@example.com",
                "Australia",
                "hardware",
                "AU-ZETA-006",
                Decimal("150000.00"),
                "critical",
                "submitted",
            ),
            (
                "Eta Software",
                "eta@example.com",
                "India",
                "software",
                "IN-ETA-007",
                Decimal("95000.00"),
                "medium",
                "under_review",
            ),
            (
                "Theta Consulting",
                "theta@example.com",
                "Netherlands",
                "consulting",
                "NL-THETA-008",
                Decimal("60000.00"),
                "low",
                "submitted",
            ),
            (
                "Iota Facilities",
                "iota@example.com",
                "Singapore",
                "facilities",
                "SG-IOTA-009",
                Decimal("110000.00"),
                "high",
                "under_review",
            ),
            (
                "Kappa Services",
                "kappa@example.com",
                "Brazil",
                "services",
                "BR-KAPPA-010",
                Decimal("22000.00"),
                "low",
                "approved",
            ),
            (
                "Lambda Hardware",
                "lambda@example.com",
                "Japan",
                "hardware",
                "JP-LAMBDA-011",
                Decimal("300000.00"),
                "high",
                "changes_requested",
            ),
            (
                "Mu Software",
                "mu@example.com",
                "Ireland",
                "software",
                "IE-MU-012",
                Decimal("180000.00"),
                "medium",
                "rejected",
            ),
            (
                "Nu Consultancy",
                "nu@example.com",
                "Sweden",
                "consulting",
                "SE-NU-013",
                Decimal("52000.00"),
                "low",
                "submitted",
            ),
            (
                "Xi Facilities",
                "xi@example.com",
                "Spain",
                "facilities",
                "ES-XI-014",
                Decimal("89000.00"),
                "medium",
                "under_review",
            ),
            (
                "Omicron Services",
                "omicron@example.com",
                "Mexico",
                "services",
                "MX-OMICRON-015",
                Decimal("41000.00"),
                "low",
                "submitted",
            ),
            (
                "Pi Hardware",
                "pi@example.com",
                "South Korea",
                "hardware",
                "KR-PI-016",
                Decimal("175000.00"),
                "critical",
                "approved",
            ),
            (
                "Rho Software",
                "rho@example.com",
                "Italy",
                "software",
                "IT-RHO-017",
                Decimal("135000.00"),
                "high",
                "changes_requested",
            ),
            (
                "Sigma Consulting",
                "sigma@example.com",
                "Switzerland",
                "consulting",
                "CH-SIGMA-018",
                Decimal("70000.00"),
                "medium",
                "rejected",
            ),
            (
                "Tau Facilities",
                "tau@example.com",
                "United Arab Emirates",
                "facilities",
                "AE-TAU-019",
                Decimal("62000.00"),
                "low",
                "under_review",
            ),
            (
                "Upsilon Services",
                "upsilon@example.com",
                "South Africa",
                "services",
                "ZA-UPSILON-020",
                Decimal("28000.00"),
                "low",
                "submitted",
            ),
            (
                "Phi Hardware",
                "phi@example.com",
                "Poland",
                "hardware",
                "PL-PHI-021",
                Decimal("210000.00"),
                "high",
                "under_review",
            ),
            (
                "Chi Software",
                "chi@example.com",
                "Portugal",
                "software",
                "PT-CHI-022",
                Decimal("145000.00"),
                "medium",
                "approved",
            ),
            (
                "Psi Consulting",
                "psi@example.com",
                "Norway",
                "consulting",
                "NO-PSI-023",
                Decimal("54000.00"),
                "low",
                "changes_requested",
            ),
            (
                "Omega Facilities",
                "omega@example.com",
                "New Zealand",
                "facilities",
                "NZ-OMEGA-024",
                Decimal("99000.00"),
                "medium",
                "submitted",
            ),
            (
                "Alpha Services",
                "alpha@example.com",
                "Denmark",
                "services",
                "DK-ALPHA-025",
                Decimal("38000.00"),
                "low",
                "approved",
            ),
        ]

        created = 0
        for (
            company_name,
            contact_email,
            country,
            category,
            tax_id,
            spend,
            risk,
            status,
        ) in demo_data:
            vendor, new = VendorApplication.objects.get_or_create(
                tax_id=tax_id,
                defaults={
                    "company_name": company_name,
                    "contact_email": contact_email,
                    "country": country,
                    "category": category,
                    "estimated_annual_spend": spend,
                    "risk_level": risk,
                    "status": status,
                },
            )
            if new:
                created += 1

        self.stdout.write(self.style.SUCCESS(f"Created {created} vendor application(s)."))
