"""Seed synthetic KYC cases for local demos."""

from datetime import date
from random import choice

from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand

from apps.kyc.models.kyc import KYCApplication
from shared.services.primitives import assignments

User = get_user_model()


class Command(BaseCommand):
    """Create a realistic set of synthetic KYC cases for demonstration."""

    help = "Seed KYC demo data (idempotent: avoids duplicates by customer identifier)."

    DEMO_COUNTRIES = [
        "United States",
        "United Kingdom",
        "Germany",
        "Canada",
        "France",
        "Australia",
        "India",
        "Netherlands",
        "Singapore",
        "Brazil",
        "Japan",
        "Ireland",
        "Sweden",
        "Spain",
        "Mexico",
        "South Korea",
        "Italy",
        "Switzerland",
        "United Arab Emirates",
        "South Africa",
    ]

    def handle(self, *args, **options):
        admin = self._get_user("admin")
        user1 = self._get_user("user1")
        demo_users = [admin, user1]

        demo_data = [
            (
                "KYC-2026-0001",
                "Alex Rivera",
                "AR-1985-US",
                "United States",
                date(1985, 6, 12),
                "passport",
                "US-AR-001",
                25,
                "low",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A001",
                "approved",
            ),
            (
                "KYC-2026-0002",
                "Bao Nguyen",
                "BN-1992-SG",
                "Singapore",
                date(1992, 3, 8),
                "national_id",
                "SG-BN-002",
                45,
                "medium",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A002",
                "under_review",
            ),
            (
                "KYC-2026-0003",
                "Chen Wei",
                "CW-1988-CN",
                "China",
                date(1988, 11, 21),
                "passport",
                "CN-CW-003FLAG",
                72,
                "high",
                "flagged",
                "PEP match; sanctions clear",
                "KYC-REF-A003",
                "escalated",
            ),
            (
                "KYC-2026-0004",
                "Daria Ivanova",
                "DI-1990-RU",
                "Russia",
                date(1990, 1, 15),
                "passport",
                "RU-DI-004",
                60,
                "medium",
                "pending",
                "",
                "",
                "pending",
            ),
            (
                "KYC-2026-0005",
                "Erik Lindqvist",
                "EL-1979-SE",
                "Sweden",
                date(1979, 9, 4),
                "national_id",
                "SE-EL-005FAIL",
                30,
                "low",
                "failed",
                "Document could not be verified",
                "KYC-REF-A005",
                "rejected",
            ),
            (
                "KYC-2026-0006",
                "Fatima Al-Rashid",
                "FA-1982-AE",
                "United Arab Emirates",
                date(1982, 7, 27),
                "passport",
                "AE-FA-006",
                55,
                "medium",
                "pending",
                "",
                "",
                "pending",
            ),
            (
                "KYC-2026-0007",
                "Giovanni Rossi",
                "GR-1995-IT",
                "Italy",
                date(1995, 12, 5),
                "drivers_license",
                "IT-GR-007",
                35,
                "low",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A007",
                "under_review",
            ),
            (
                "KYC-2026-0008",
                "Hannah Müller",
                "HM-1987-DE",
                "Germany",
                date(1987, 4, 18),
                "national_id",
                "DE-HM-008FLAG",
                80,
                "high",
                "flagged",
                "Sanctions list match",
                "KYC-REF-A008",
                "escalated",
            ),
            (
                "KYC-2026-0009",
                "Isaac Omondi",
                "IO-1991-KE",
                "Kenya",
                date(1991, 8, 30),
                "passport",
                "KE-IO-009",
                40,
                "medium",
                "pending",
                "",
                "",
                "pending",
            ),
            (
                "KYC-2026-0010",
                "Julia Fernandez",
                "JF-1984-ES",
                "Spain",
                date(1984, 2, 14),
                "passport",
                "ES-JF-010",
                20,
                "low",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A010",
                "approved",
            ),
            (
                "KYC-2026-0011",
                "Kenji Tanaka",
                "KT-1993-JP",
                "Japan",
                date(1993, 10, 9),
                "drivers_license",
                "JP-KT-011FAIL",
                65,
                "high",
                "failed",
                "Identity mismatch",
                "KYC-REF-A011",
                "rejected",
            ),
            (
                "KYC-2026-0012",
                "Lina Petrov",
                "LP-1989-BG",
                "Bulgaria",
                date(1989, 5, 22),
                "national_id",
                "BG-LP-012",
                50,
                "medium",
                "pending",
                "",
                "",
                "pending",
            ),
            (
                "KYC-2026-0013",
                "Marco Silva",
                "MS-1986-BR",
                "Brazil",
                date(1986, 6, 1),
                "passport",
                "BR-MS-013",
                28,
                "low",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A013",
                "under_review",
            ),
            (
                "KYC-2026-0014",
                "Nadia Kowalski",
                "NK-1994-PL",
                "Poland",
                date(1994, 12, 17),
                "national_id",
                "PL-NK-014FLAG",
                75,
                "high",
                "flagged",
                "PEP match; sanctions clear",
                "KYC-REF-A014",
                "escalated",
            ),
            (
                "KYC-2026-0015",
                "Oscar Williams",
                "OW-1983-CA",
                "Canada",
                date(1983, 3, 3),
                "drivers_license",
                "CA-OW-015",
                33,
                "low",
                "pending",
                "",
                "",
                "pending",
            ),
            (
                "KYC-2026-0016",
                "Priya Sharma",
                "PS-1990-IN",
                "India",
                date(1990, 11, 11),
                "passport",
                "IN-PS-016",
                48,
                "medium",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A016",
                "under_review",
            ),
            (
                "KYC-2026-0017",
                "Quentin Dubois",
                "QD-1981-FR",
                "France",
                date(1981, 8, 24),
                "national_id",
                "FR-QD-017FAIL",
                70,
                "high",
                "failed",
                "Document expired",
                "KYC-REF-A017",
                "rejected",
            ),
            (
                "KYC-2026-0018",
                "Rosa Martinez",
                "RM-1996-MX",
                "Mexico",
                date(1996, 4, 7),
                "passport",
                "MX-RM-018",
                22,
                "low",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A018",
                "approved",
            ),
            (
                "KYC-2026-0019",
                "Samuel Anderson",
                "SA-1980-GB",
                "United Kingdom",
                date(1980, 7, 19),
                "drivers_license",
                "GB-SA-019",
                58,
                "medium",
                "pending",
                "",
                "",
                "pending",
            ),
            (
                "KYC-2026-0020",
                "Tina O'Brien",
                "TO-1992-IE",
                "Ireland",
                date(1992, 2, 28),
                "passport",
                "IE-TO-020FLAG",
                85,
                "high",
                "flagged",
                "Adverse media flag",
                "KYC-REF-A020",
                "escalated",
            ),
            (
                "KYC-2026-0021",
                "Ursula Schmidt",
                "US-1988-AT",
                "Austria",
                date(1988, 10, 13),
                "national_id",
                "AT-US-021",
                15,
                "low",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A021",
                "approved",
            ),
            (
                "KYC-2026-0022",
                "Victor Kim",
                "VK-1997-KR",
                "South Korea",
                date(1997, 1, 6),
                "passport",
                "KR-VK-022",
                42,
                "medium",
                "pending",
                "",
                "",
                "pending",
            ),
            (
                "KYC-2026-0023",
                "Wendy Clark",
                "WC-1985-AU",
                "Australia",
                date(1985, 9, 25),
                "drivers_license",
                "AU-WC-023",
                37,
                "low",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A023",
                "under_review",
            ),
            (
                "KYC-2026-0024",
                "Xavier Moreau",
                "XM-1984-CH",
                "Switzerland",
                date(1984, 5, 31),
                "passport",
                "CH-XM-024FAIL",
                68,
                "high",
                "failed",
                "Document could not be verified",
                "KYC-REF-A024",
                "rejected",
            ),
            (
                "KYC-2026-0025",
                "Yuki Tan",
                "YT-1993-NZ",
                "New Zealand",
                date(1993, 7, 8),
                "national_id",
                "NZ-YT-025",
                29,
                "low",
                "verified",
                "Sanctions clear; PEP clear",
                "KYC-REF-A025",
                "under_review",
            ),
            (
                "KYC-2026-0026",
                "Zara Hamed",
                "ZH-1986-EG",
                "Egypt",
                date(1986, 12, 2),
                "passport",
                "EG-ZH-026",
                52,
                "medium",
                "pending",
                "",
                "",
                "pending",
            ),
        ]

        created = 0
        for (
            identifier,
            customer_name,
            _,
            country,
            date_of_birth,
            document_type,
            document_id,
            risk_score,
            risk_level,
            provider_status,
            screening_flags,
            provider_reference,
            status,
        ) in demo_data:
            case, new = KYCApplication.objects.get_or_create(
                customer_identifier=identifier,
                defaults={
                    "customer_name": customer_name,
                    "country": country,
                    "date_of_birth": date_of_birth,
                    "document_type": document_type,
                    "document_identifier": document_id,
                    "risk_score": risk_score,
                    "risk_level": risk_level,
                    "provider_verification_status": provider_status,
                    "screening_flags": screening_flags,
                    "provider_reference": provider_reference,
                    "status": status,
                },
            )
            if new:
                created += 1
                if status in ("under_review", "escalated") and demo_users:
                    user = choice(demo_users)
                    assignments.assign(obj=case, assigned_to=user, assigned_by=user)

        self.stdout.write(self.style.SUCCESS(f"Created {created} KYC case(s)."))

    def _get_user(self, username):
        try:
            return User.objects.get(username=username)
        except User.DoesNotExist:
            return None
