# Generated by Django 5.2.17 on 2026-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('services', 'Services'), ('software', 'Software'), ('hardware', 'Hardware'), ('consulting', 'Consulting'), ('facilities', 'Facilities')], default='services', max_length=50)),
                ('tax_id', models.CharField(max_length=100)),
                ('estimated_annual_spend', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='vendors_ven_status_c19b9c_idx'), models.Index(fields=['risk_level', '-created_at'], name='vendors_ven_risk_le_320137_idx'), models.Index(fields=['category', '-created_at'], name='vendors_ven_categor_05bfbf_idx'), models.Index(fields=['company_name'], name='vendors_ven_company_40b7f9_idx'), models.Index(fields=['country'], name='vendors_ven_country_11a337_idx')],
            },
        ),
    ]
