# Generated by Django 5.2.17 on 2026-08-29 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_identifier', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's License")], default='passport', max_length=50)),
                ('document_identifier', models.CharField(max_length=100)),
                ('risk_score', models.PositiveSmallIntegerField(default=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('provider_verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('screening_flags', models.CharField(blank=True, help_text="Short screening summary, e.g. 'Sanctions clear; PEP flag'.", max_length=200)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('escalated', 'Escalated'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='kyc_kycapp_status_5d6b6c_idx'), models.Index(fields=['risk_level', '-created_at'], name='kyc_kycapp_risk_le_9e4e5a_idx'), models.Index(fields=['provider_verification_status', '-created_at'], name='kyc_kycapp_provide_7f8c9b_idx'), models.Index(fields=['customer_name'], name='kyc_kycapp_custome_1a2b3c_idx'), models.Index(fields=['country'], name='kyc_kycapp_country_4d5e6f_idx'), models.Index(fields=['customer_identifier'], name='kyc_kycapp_custome_7g8h9i_idx')],
            },
        ),
    ]
