# Generated by Django 5.2.17 on 2026-08-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kycapplication',
            new_name='kyc_kycappl_status_99de32_idx',
            old_name='kyc_kycapp_status_5d6b6c_idx',
        ),
        migrations.RenameIndex(
            model_name='kycapplication',
            new_name='kyc_kycappl_risk_le_f2e949_idx',
            old_name='kyc_kycapp_risk_le_9e4e5a_idx',
        ),
        migrations.RenameIndex(
            model_name='kycapplication',
            new_name='kyc_kycappl_provide_9ebe7f_idx',
            old_name='kyc_kycapp_provide_7f8c9b_idx',
        ),
        migrations.RenameIndex(
            model_name='kycapplication',
            new_name='kyc_kycappl_custome_7ce751_idx',
            old_name='kyc_kycapp_custome_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='kycapplication',
            new_name='kyc_kycappl_country_002c78_idx',
            old_name='kyc_kycapp_country_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='kycapplication',
            new_name='kyc_kycappl_custome_0da4ab_idx',
            old_name='kyc_kycapp_custome_7g8h9i_idx',
        ),
    ]
